### PR TITLE
License cleanup + fix file permissions for images

### LINKED ISSUE #27: License compatible logos/images
Before we publicly release the materials we need to make sure that everything we have is license compatible.

I think the biggest question is: is the MDA logo CC-BY-4-SA compatible? (pinging @orbeckst and @jbarnoud here who might have a better idea of the MDA logo's licensing and cross CC-BY version compatibility).

The other one is whether the logos used in the first lecture are all suitable license-wise. @fiona-naughton can you check this?

### PR DESCRIPTION
**Pull request by IAlibay**
Fixes #27

- Adds the MDA logo details to the license
- Clarifies the REAMDE license blurb
- Removes unlicensed surf/prace logos
- Fixes permissions on pngs (WSL makes a lot of random things executable for no reason)

### CODE REVIEW

File: LICENSE.CC-BY-SA [hunk 1]
```diff
@@ -426,3 +426,24 @@ public licenses.
 
 Creative Commons may be contacted at creativecommons.org.
 
+
+=======================================================================
+
+MDAnalysis logo
+
+he MDAnalysis 'Atom' logo was created by Christian Beckstein and is
```
Comment (orbeckst) [inline LICENSE.CC-BY-SA]:
```suggestion
The MDAnalysis 'Atom' logo was created by Christian Beckstein and is
```

**Review by orbeckst — APPROVED** [review]
minor typo (see comments), otherwise LGTM
